city = input("Enter a city: ")
city = city.strip()
city = city.title()
country = input("Enter a country: ")
country = country.strip()
country = country.title()
landmark = input("Enter a landmark: ")
landmark = landmark.strip()
landmark = landmark.title()
print("Destination:", city, "-", country)
print("Visit:", landmark)
